apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: game-backend-pod-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-backend-pod-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: game-backend-pod-manager
subjects:
  - kind: ServiceAccount
    name: game-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-backend-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-backend-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: game-backend-node-reader
subjects:
  - kind: ServiceAccount
    name: game-backend
    namespace: default
